import './globals.css'

import { SpeedInsights } from '@vercel/speed-insights/next'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: "Hello! I'm Michal Zajac!",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="w-screen overflow-x-hidden">
        {children}
        <SpeedInsights />
      </body>
    </html>
  )
}
